### ISSUE TITLE
[Proposal] Bibliography object

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#58]
## What is your proposed change?

Proposal is to create a bibliography object with new fields including

Title
Authors 
Year
Url 

The object will be an array with the description ‘An array of one of more publications that relate to or have made use of this dataset’

## Why is this not covered by the existing model?

The current version of the standard contains `biblio_title` (Authors/year/title of publication) and `biblio_url` (URL of publication). 

## Can you provide an example?
```

"bibliography": [
  {
	"title": "Title of the publication",
	"authors": [
  	"Jane Brown",
  	"Sherlock Bungalow",
  	"James L Watson",
	],
	"year": "2023-05-16T07:38:31.0Z",
	"url": "https://website.com"
  }
]
```

**Comment by duncandewhurst** [comment]
I think that we need to clarify the semantics of this field. A bibliography is a list of the publications referenced in scholarly work. However, according to the proposed description, we're talking about the reverse of that, i.e. a list of publications that reference this dataset.

DCAT has an [isReferencedBy](https://www.w3.org/TR/vocab-dcat/#Property:resource_is_referenced_by) property, which seems like a more appropriate model.

**Comment by stufraser1** [comment]
DCAT isReferencedBy seems to work. Would it allow the fields suggested above?
I would like to suggest adding DOI as a reference to the resource, instead of or additional to url

**Comment by duncandewhurst** [comment]
DCAT doesn't specify properties so we can add our own. I suggest the following based on Schema.org's `CreativeWork`:

| Field | Title | Description | Type | Items |
| -- | -- | -- | -- | -- |
| `referencedBy` | Referenced by | Related resources, such as publications, that reference, cite, or otherwise point to the dataset. | array | `RelatedResource` |

| Definition | Title | Description | Type |
| -- | -- | -- | -- |
| `RelatedResource` | Related resource |  A related resource, such as a publication, that references, cites, or otherwise points to a dataset. | object |

| Property | Title | Description | Type | Format |
| -- | -- | -- | -- | -- |
| `name` | Name | The name of the resource. | string | |
| `authorNames` | Author names | The names of the authors of the resource. | array (string) | |
| `datePublished` | Publication date | The date that the resource was first published. | string | date |
| `url` | Uniform Resource Locator | The uniform resource locator for the resource, e.g. the web address at which the resource can be accessed. | string | iri |
| `doi` | Digital Object Identifier | The digital object identifier for the resource. | string | |

Instad of `authorNames`, we could provide a more structured model with an `authors` property that is an array of the `Entity` objects proposed in https://github.com/GFDRR/rdl-standard/issues/61#issuecomment-1563662763, but that would add an extra layer of nesting and an extra table in tabular formats. Using `authorNames` rather than `authors` leaves that option open for the future.

**Comment by odscrachel** [comment]
Note that adding 'The name or title of the resource.' to the `name` description would help to clarify what's needed here.
