### ISSUE TITLE
[Proposal] Top level period field 

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#67]
## What is your proposed change?

To create a top level `period` field with the following attributes

Title | Field name | Description | Field Type
| ------------- | ------------- | ------------- | ------------- |
| Period  | `period` | The period of time covered in the dataset given as a year or range of years. If there are multiple resources, each covering a different period of time, this value should be the full range covered by all of the resources.  | string

## Why is this not covered by the existing model?

This replaces `temporal_extent` (Years covered in the analysis (one or range) e.g. "2020" or "1980-2015") from DDH_v0.2.xlsx

**Comment by duncandewhurst** [comment]
I think that we should align the name of this field with the [`temporal` property](https://www.w3.org/TR/vocab-dcat/#Property:dataset_temporal) from DCAT, which I proposed reusing at the resource/distribution level in https://github.com/GFDRR/rdl-standard/issues/54#issuecomment-1562236029.

In order to make it possible to validate the data and to further align with DCAT, I think that temporal coverage should be modelled as a `Period` object. Ideally, that would have `.startDate` and `.endDate` properties expressed as full dates, e.g. "2020-01-01". However, if it is possible for only the start and end years to be known, then we can instead have `startYear` and `endYear` properties:

| Property | Title | Description | Type |
| -- | -- | -- | -- |
| `startYear` | Start year | The year in which the period begins. | integer |
| `endYear` | End year | The year in which the period ends. | integer |

**Comment by duncandewhurst** [comment]
Noting that we should align this with the modelling proposed in https://github.com/GFDRR/rdl-standard/issues/54#issuecomment-1571084236:

> > ```
> > * `start` and `end` could refer to day, month, year... E.g. agricultural damage for first crop season of 2010. But we can also have an individual month/year. E.g. Population layer for 2019;  then user would enter the same `start` and `end`?
> > ```
> 
> In that case, to avoid a proliferation of potentially contradictory fields, I think it would be better to just have `.start` and `.end` and to allow them to be expressed as years, months or dates using a subset of ISO8601:
> 
>     * Year: YYYY
> 
>     * Month: YYYY-MM
> 
>     * Day: YYYY-MM-DD
> 
> 
> In terms of validation, we can either author a regex for the [`pattern` keyword](https://json-schema.org/understanding-json-schema/reference/string.html#id6) or a custom [format](https://json-schema.org/understanding-json-schema/reference/string.html#format) and associated format validator. I think that a regex is preferable as it will be compatible with any validation tooling with support for JSON Schema, but some extra work will be required to make error messages user-friendly.
> 
> Regarding the example of a population layer for 2019, if no more detail on the exact dates is known, then both `.start` and `.end` should be set to '2019'. We provide guidance in the field description or documentation.

**Comment by odscjen** [comment]
The `temporal` object will also be referenced by `exposure.reference_year`

**Comment by odscjen** [comment]
@stufraser1 can we clarify what `year` is used for which isn't already covered by allowing `start` and `end` to be the same year?

**Comment by odscjen** [comment]
answer to my question in https://github.com/GFDRR/rdl-standard/issues/62#issuecomment-1612483522

**Comment by odscjen** [comment]
see https://github.com/GFDRR/rdl-standard/issues/62#issuecomment-1612869346 for potential change

**Comment by odscjen** [comment]
addressed by https://github.com/GFDRR/rdl-standard/pull/104
