### ISSUE TITLE
[Proposal] Hazard footprint identifier 

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#70]
## What is your proposed change?

To create a new `event_id` field within the `footprint_set` object that sits within the `hazard` component. The field will have the following attributes

Title | Field name | Description | Type
| ------------- | ------------- | ------------- | ------------- |
Event identifier  | `footprint_set.event_id` | The id of the event that this footprint is based upon. | string

## What is the context or reason for the change?

To make clear which event a footprint belongs to.

**Comment by stufraser1** [comment]
Need this event_id but I thought it already existed, is this new?

**Comment by duncandewhurst** [comment]
Rather than relying on identifiers and cross-referencing, is there a reason not to nest footprints under the event that they relate to? That is what the diagram on https://docs.riskdatalibrary.org/hazard.html shows:

![image](https://github.com/GFDRR/rdl-standard/assets/19265814/d266026d-b539-407b-9969-56a19d2942f6)

I think the only reason to use cross-referencing is if one footprint can relate to more than one event.

In https://github.com/GFDRR/rdl-standard/issues/59, we're already proposing to nest events under event sets, so if we then nested footprints under events it would look like this:

```json
{
  "hazard": {
    "event_set": {
      "events": [
        {
          // event A
          "footprints": [
            {
              // footprint 1
            },
            {
              // footprint 2
            }
          ]
        },
        {
          // event B
          "footprints": [
            {
              // footprint 3
            },
            {
              // footprint 4
            }
          ]
        },
      ]
    }
  }
}
```
```

**Comment by stufraser1** [comment]
This nesting concept is how we set the schema up originally.
Footprint ID was used in the original database schema to link a set of footprint data to an event in another table. 

It is possible that users would provide data with each footprint in a set of multiple footprints, provided in one csv per footprint. We just need to ensure that if multiple footprint files are provided, they can be linked back to the relevant event ID.

**Comment by duncandewhurst** [comment]
We can have `.id` fields on event sets, events and footprints to support tabular representations and we can have nesting to avoid the need for cross-referencing and look-ups when working with the data in JSON format. Sound good?
