### ISSUE TITLE
[Proposal] Vulnerability spatial scale codelist

### ISSUE THREAD

**Issue by odscrachel** [GFDRR/rdl-standard#77]
## What is your proposed change?

To create a new codelist for the field `spatial_scale` within the vulnerability component. 

Title | Field name | Description | Type | Codelist
| ------------- | ------------- | ------------- | ------------- | ------------- |
Administrative spatial scale  | `spatial_scale` | The administrative spatial scale the vulnerability function used in the modelled scenario(s) applies to. | string | global, regional, national, sub-national

**Comment by duncandewhurst** [comment]
Is there any need for a code between regional and national? The United Nations Statistics Division's [M49 coding classification](https://unstats.un.org/unsd/methodology/m49/overview/) has sub-regions (e.g. Sub-Saharan Africa) and intermediate regions (e.g. Eastern Africa).

In any case, we'll need to be clear in the description of 'regional' that it refers to supranational regions rather than subnational regions.

**Comment by matamadio** [comment]
I think "region" will be enough to include both sub-regions and intermediate.

> In any case, we'll need to be clear in the description of 'regional' that it refers to supranational regions rather than subnational regions.
The order of the options should help but yes, description should specify these are supranational regions.

**Comment by odscrachel** [comment]
So is the agreement that we will update the codelist to be:
| Codelist|
| ------------- | 
|global, regional, national|

and update the documentation to advise that region refers to supranational regions?

**Comment by duncandewhurst** [comment]
Was there a reason for dropping the sub-national code?

**Comment by matamadio** [comment]
`Was there a reason for dropping the sub-national code?`
This was originally referring to spatial applicability of vulnerability function, which usually comes at the national level or up.
However, when drawing empirical damage functions from a specific event, sub-national reference could matter.
Thus:

| Codelist|
| ------------- | 
|global, regional, national, sub-national|

But then this would becomes basically a duplicate of other location attributes? See #52

**Comment by duncandewhurst** [comment]
> Codelist
> global, regional, national, sub-national

Sounds good.

> But then this would becomes basically a duplicate of other location attributes? See https://github.com/GFDRR/rdl-standard/issues/52

The field and codelist proposed in this issue have different semantics from the `spatial` object proposed in #52. The `spatial` object describes a specific geographic area as either a list of countries, a list of gazetteer entries, a bounding box, a polygon or a centroid. The `spatial_scale` field in this issue classifies a geographic area as either global, regional, national, or sub-national, without reference to a specific region or country etc.

That said, I think it would make sense to align the modelling of spatial coverage wherever it appears in the schema (dataset, vulnerability, hazard event location etc.) so we could replace `spatial_scale` with the `spatial` object and add `.scale` as a child property. The `.scale` property can be required when used in the context of vulnerability and the other properties of `spatial` can be optional in case publishers want to provide more detail on the spatial coverage of the vulnerability function. Sound good?

**Comment by stufraser1** [comment]
Code,Label,Definition
global,global,"Applicable at the global scale, due to being developed using global data"
regional,regional,"Applicable at the regional (multi-country) scale, developed using regional scale data"
national,national,"Applicable at the national scale, developed using national data"
sub-national,sub-national,"Applicable at the subnational scale, developed using subnational data"
