### ISSUE TITLE
[Docs update] Check normative words in guidance

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-standard#90]
## What is the context or reason for the change?
Reviewing guidance / docs for normative words.
Normative words should be only used in areas requiring governance approval for changes.

Please provide a short description of the reason for proposing the change.
The following normative words must only be used within normative [content](https://docs.google.com/document/d/13g1SZO3ZSHbkymtc69lQOu9vB9vlZVZnodAcxC50l1M/edit#heading=h.yt2d68tqtz0m):

MUST 
MUST NOT
REQUIRED
SHALL
SHALL NOT
SHOULD
SHOULD NOT
RECOMMENDED
MAY
OPTIONAL

## What is your proposed change?
Review the sections below, complete to-do list.

Please specify the sections that are to be modified or replaced by indicating start and end of the edit in the current text.
- [x]  Overview
- [x] Core standards
- [x] Use cases
- [x] History and roadmap
- [x] Taxonomies
- [x] Taxonomies - H
- [x] Taxonomies - E
- [x] Taxonomies - V
- [x] Taxonomies - L
- [x] Packaging
- [x] data formats
- [x] rdl metadata
- [x] rdl colleciton
- [x] glossary

**Comment by stufraser1** [comment]
@odscrachel 
Ln48 of https://github.com/GFDRR/rdl-standard/edit/docs.mat/docs/guides/ddh-rdl.md: "When all required (and optional) information has been entered, click on `Save as draft`. The dataset will appear under `My datasets` list." 
Since this is describing data, and not giving instruction, can this use. of 'required' and 'optional' be retained?

**Comment by duncandewhurst** [comment]
In other standards, we've found it easiest to have a hard rule that normative keywords must only be used in the reference (normative) section of the documentation. Otherwise, you can end up having lots of discussions about when it is and isn't OK to use the keywords.

In this case, it wouldn't really make sense to replace 'required' and 'optional' with non-normative synonyms. However, having required and optional fields in a form is a pretty universal concept so I don't think that part of the sentence is really serving a specific purpose with respect to RDLS or the World Bank Data Catalog. Therefore, I would replace it with:

> Once done, click **save as draft**.

Side note: The [Google developer documentation style guide](https://developers.google.com/style/ui-elements) has some really helpful guidance on how to describe UI elements and interaction, which can help to keep that type of documentation page clear and concise. Similarly, Google's free online [technical writing courses](https://developers.google.com/tech-writing/overview) are extremely useful and applicable to writing standards documentation. The self-led part of technical writing one alone helped my writing tremendously.

**Comment by stufraser1** [comment]
Checked and replaced where needed - to date. Closing
